module VerifyExamples.Documentation.Combinations0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Documentation exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#combinations: \n\n    combinations [1, 2, 3]\n    --> [[1,2,3],[1,2],[1,3],[1],[2,3],[2],[3],[]]" <|
        \() ->
            Expect.equal
                (
                combinations [1, 2, 3]
                )
                (
                [[1,2,3],[1,2],[1,3],[1],[2,3],[2],[3],[]]
                )