module VerifyExamples.Documentation.Tails0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Documentation exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#tails: \n\n    tails [1, 2, 3]\n    --> [[1, 2, 3], [2, 3], [3], []]" <|
        \() ->
            Expect.equal
                (
                tails [1, 2, 3]
                )
                (
                [[1, 2, 3], [2, 3], [3], []]
                )